const state={page:"dashboard",transactions:[],students:[],fees:[]};
const content=document.getElementById("content"),sidebar=document.getElementById("sidebar"),overlay=document.getElementById("overlay"),modalBackdrop=document.getElementById("modalBackdrop"),modal=document.getElementById("modal"),pageTitle=document.getElementById("pageTitle");
const titles={dashboard:"Dashboard",transactions:"Income / Expenses",daily:"Today's Total",students:"Students Data",fees:"Student Fees"};
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>navigate(btn.dataset.page)));
document.getElementById("menuBtn").addEventListener("click",()=>{sidebar.classList.add("open");overlay.classList.add("show")});overlay.addEventListener("click",closeMenu);
function closeMenu(){sidebar.classList.remove("open");overlay.classList.remove("show")}
function navigate(page){state.page=page;pageTitle.textContent=titles[page];document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));closeMenu();render()}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN")}
function render(){if(state.page==="dashboard")renderDashboard();if(state.page==="transactions")renderTransactions();if(state.page==="daily")renderDaily();if(state.page==="students")renderStudents();if(state.page==="fees")renderFees()}
function renderDashboard(){const income=state.transactions.filter(x=>x.type==="Income").reduce((a,x)=>a+Number(x.amount),0),expense=state.transactions.filter(x=>x.type==="Expense").reduce((a,x)=>a+Number(x.amount),0),due=state.fees.reduce((a,x)=>a+Math.max(0,Number(x.due)),0);content.innerHTML=`<div class="hero"><div><span class="eyebrow">STAGE 1</span><h2>Welcome to Dingel Hafizia App</h2><p>Clean frontend foundation for Financial Management and Student Management. Backend/Firebase is intentionally excluded at this stage.</p></div><div class="hero-mark">DH</div></div><h2 class="section-title">Overview</h2><div class="grid"><div class="card"><div class="stat-label">Total Income</div><div class="stat-value">${money(income)}</div><div class="stat-note">Frontend data only</div></div><div class="card"><div class="stat-label">Total Expenses</div><div class="stat-value">${money(expense)}</div><div class="stat-note">Frontend data only</div></div><div class="card"><div class="stat-label">Students</div><div class="stat-value">${state.students.length}</div><div class="stat-note">Student profiles</div></div><div class="card"><div class="stat-label">Fee Due</div><div class="stat-value">${money(due)}</div><div class="stat-note">Outstanding amount</div></div></div><h2 class="section-title">Modules</h2><div class="module-grid"><div class="card module-card"><div><h3>Financial Management</h3><p>Income, expenses, transaction history and today's totals.</p></div><div class="module-icon">৳</div></div><div class="card module-card"><div><h3>Student Management</h3><p>Student profiles, fee collection and outstanding dues.</p></div><div class="module-icon">♙</div></div></div>`}
function renderTransactions(){content.innerHTML=`<div class="page-head"><div><h2>Income / Expenses</h2><p>Entry and history of all financial transactions.</p></div><button class="btn btn-primary" onclick="openTransactionModal()">+ New Transaction</button></div><div class="toolbar"><input class="input" id="transactionSearch" placeholder="Search transactions..." oninput="filterTransactions()"><select class="select" id="transactionFilter" onchange="filterTransactions()"><option value="All">All</option><option>Income</option><option>Expense</option></select></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Amount</th></tr></thead><tbody id="transactionRows"></tbody></table></div></div>`;filterTransactions()}
function filterTransactions(){const q=(document.getElementById("transactionSearch")?.value||"").toLowerCase(),f=document.getElementById("transactionFilter")?.value||"All",rows=state.transactions.filter(x=>(f==="All"||x.type===f)&&`${x.category} ${x.description}`.toLowerCase().includes(q)),body=document.getElementById("transactionRows");body.innerHTML=rows.length?rows.map(x=>`<tr><td>${x.date}</td><td><span class="badge ${x.type.toLowerCase()}">${x.type}</span></td><td>${x.category}</td><td>${x.description||"—"}</td><td><strong>${money(x.amount)}</strong></td></tr>`).join(""):`<tr><td colspan="5"><div class="empty"><strong>No transactions yet</strong>Add an income or expense to see it here.</div></td></tr>`}
function renderDaily(){const today=new Date().toISOString().slice(0,10),list=state.transactions.filter(x=>x.date===today),income=list.filter(x=>x.type==="Income").reduce((a,x)=>a+Number(x.amount),0),expense=list.filter(x=>x.type==="Expense").reduce((a,x)=>a+Number(x.amount),0);content.innerHTML=`<div class="page-head"><div><h2>Today's Total</h2><p>Daily summary of income and expenses.</p></div></div><div class="summary-grid"><div class="card summary-card"><div class="stat-label">Today's Income</div><div class="big">${money(income)}</div></div><div class="card summary-card"><div class="stat-label">Today's Expenses</div><div class="big">${money(expense)}</div></div><div class="card summary-card"><div class="stat-label">Today's Balance</div><div class="big">${money(income-expense)}</div></div></div><h2 class="section-title">Today's Transactions</h2><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Type</th><th>Category</th><th>Description</th><th>Amount</th></tr></thead><tbody>${list.length?list.map(x=>`<tr><td><span class="badge ${x.type.toLowerCase()}">${x.type}</span></td><td>${x.category}</td><td>${x.description||"—"}</td><td><strong>${money(x.amount)}</strong></td></tr>`).join(""):`<tr><td colspan="4"><div class="empty"><strong>No transactions today</strong>Today's financial summary is empty.</div></td></tr>`}</tbody></table></div></div>`}
function renderStudents(){content.innerHTML=`<div class="page-head"><div><h2>Students Data</h2><p>Student profiles and information.</p></div><button class="btn btn-primary" onclick="openStudentModal()">+ Add Student</button></div><div class="toolbar"><input class="input" id="studentSearch" placeholder="Search by name or class..." oninput="filterStudents()"></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Name</th><th>Class</th><th>Guardian</th><th>Phone</th><th>Status</th></tr></thead><tbody id="studentRows"></tbody></table></div></div>`;filterStudents()}
function filterStudents(){const q=(document.getElementById("studentSearch")?.value||"").toLowerCase(),rows=state.students.filter(x=>`${x.name} ${x.className} ${x.guardian}`.toLowerCase().includes(q));document.getElementById("studentRows").innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.className}</td><td>${x.guardian||"—"}</td><td>${x.phone||"—"}</td><td><span class="badge paid">Active</span></td></tr>`).join(""):`<tr><td colspan="5"><div class="empty"><strong>No students yet</strong>Add a student profile to begin.</div></td></tr>`}
function renderFees(){content.innerHTML=`<div class="page-head"><div><h2>Student Fees</h2><p>Fee payments and outstanding dues.</p></div><button class="btn btn-primary" onclick="openFeeModal()">+ Record Fee</button></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Student</th><th>Month</th><th>Fee</th><th>Paid</th><th>Due</th><th>Status</th></tr></thead><tbody>${state.fees.length?state.fees.map(x=>`<tr><td><strong>${x.student}</strong></td><td>${x.month}</td><td>${money(x.fee)}</td><td>${money(x.paid)}</td><td>${money(x.due)}</td><td><span class="badge ${Number(x.due)>0?"due":"paid"}">${Number(x.due)>0?"Due":"Paid"}</span></td></tr>`).join(""):`<tr><td colspan="6"><div class="empty"><strong>No fee records yet</strong>Record a student's fee payment to see it here.</div></td></tr>`}</tbody></table></div></div>`}
function openModal(html){modal.innerHTML=html;modalBackdrop.classList.add("show")}function closeModal(){modalBackdrop.classList.remove("show");modal.innerHTML=""}modalBackdrop.addEventListener("click",e=>{if(e.target===modalBackdrop)closeModal()});
function openTransactionModal(){openModal(`<div class="modal-head"><h3>New Transaction</h3><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveTransaction(event)"><div class="form-grid"><div class="field"><label>Type</label><select class="select" name="type"><option>Income</option><option>Expense</option></select></div><div class="field"><label>Date</label><input class="input" type="date" name="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Category</label><input class="input" name="category" placeholder="e.g. Fee / Food" required></div><div class="field"><label>Amount</label><input class="input" type="number" min="0" step="0.01" name="amount" required></div><div class="field full"><label>Description</label><input class="input" name="description" placeholder="Optional description"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary">Save Transaction</button></div></form>`)}
function saveTransaction(e){e.preventDefault();const f=new FormData(e.target);state.transactions.unshift(Object.fromEntries(f.entries()));state.transactions[0].amount=Number(state.transactions[0].amount);closeModal();render()}
function openStudentModal(){openModal(`<div class="modal-head"><h3>Add Student</h3><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveStudent(event)"><div class="form-grid"><div class="field full"><label>Student Name</label><input class="input" name="name" required></div><div class="field"><label>Class</label><input class="input" name="className" placeholder="Class" required></div><div class="field"><label>Guardian</label><input class="input" name="guardian"></div><div class="field full"><label>Phone</label><input class="input" name="phone" inputmode="tel"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary">Save Student</button></div></form>`)}
function saveStudent(e){e.preventDefault();state.students.unshift(Object.fromEntries(new FormData(e.target).entries()));closeModal();render()}
function openFeeModal(){const options=state.students.map(s=>`<option value="${s.name}">${s.name}</option>`).join("");openModal(`<div class="modal-head"><h3>Record Student Fee</h3><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveFee(event)"><div class="form-grid"><div class="field full"><label>Student</label><select class="select" name="student" required>${options||'<option value="">Add a student first</option>'}</select></div><div class="field"><label>Month</label><input class="input" name="month" placeholder="September 2026" required></div><div class="field"><label>Total Fee</label><input class="input" type="number" min="0" name="fee" required></div><div class="field full"><label>Paid Amount</label><input class="input" type="number" min="0" name="paid" required></div></div><div class="modal-actions"><button type="button" class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary" ${state.students.length?"":"disabled"}>Save Fee</button></div></form>`)}
function saveFee(e){e.preventDefault();const x=Object.fromEntries(new FormData(e.target).entries());x.fee=Number(x.fee);x.paid=Number(x.paid);x.due=Math.max(0,x.fee-x.paid);state.fees.unshift(x);closeModal();render()}
render();