const safeLoad=(key,fallback=[])=>{try{const v=JSON.parse(localStorage.getItem(key)||"null");return Array.isArray(v)?v:fallback}catch(e){return fallback}};
const state={page:"dashboard",transactions:safeLoad("dh_transactions"),students:safeLoad("dh_students"),fees:safeLoad("dh_fees")};
const $=id=>document.getElementById(id),content=$("content"),sidebar=$("sidebar"),overlay=$("overlay"),modalBackdrop=$("modalBackdrop"),modal=$("modal"),pageTitle=$("pageTitle");
const titles={dashboard:"Dashboard",transactions:"Income / Expenses",categories:"Categories",daily:"Today's Total",students:"Students Data",fees:"Student Fees",teachers:"Teacher Management",permissions:"Role & Permissions",accounts:"Accounts Overview",settings:"Settings"};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
function persist(){localStorage.setItem("dh_transactions",JSON.stringify(state.transactions));localStorage.setItem("dh_students",JSON.stringify(state.students));localStorage.setItem("dh_fees",JSON.stringify(state.fees))}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]))}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.page)));$("menuBtn").addEventListener("click",()=>{sidebar.classList.add("open");overlay.classList.add("show")});overlay.addEventListener("click",closeMenu);modalBackdrop.addEventListener("click",e=>{if(e.target===modalBackdrop)closeModal()});
function closeMenu(){sidebar.classList.remove("open");overlay.classList.remove("show")}
function navigate(page){if(!titles[page])page="dashboard";state.page=page;pageTitle.textContent=titles[page];document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));closeMenu();render()}
function openModal(html){modal.innerHTML=html;modalBackdrop.classList.add("show")}
function closeModal(){modalBackdrop.classList.remove("show");modal.innerHTML=""}
function render(){
  if(state.page==="transactions" && typeof window.renderTransactions==="function") return window.renderTransactions();
  if(state.page==="categories" && typeof window.renderCategories==="function") return window.renderCategories();
  const fn={dashboard:renderDashboard,daily:renderDaily,students:renderStudents,fees:renderFees,teachers:window.renderTeachers,permissions:window.renderPermissions,accounts:window.renderAccounts,settings:window.renderSettings}[state.page];
  if(typeof fn==="function")return fn();
  renderDashboard();
}
function renderDashboard(){const income=state.transactions.filter(x=>x.type==="Income").reduce((a,x)=>a+Number(x.amount||0),0),expense=state.transactions.filter(x=>x.type==="Expense").reduce((a,x)=>a+Number(x.amount||0),0),due=state.fees.reduce((a,x)=>a+Number(x.due||0),0);content.innerHTML=`<div class="hero"><div><span class="eyebrow">DINGEL HAFIZIA APP</span><h2>Welcome to Dingel Hafizia App</h2><p>Financial Management and Student Management frontend. Data is stored locally in this browser for now; no Firebase/backend is used.</p></div><div class="hero-mark">DH</div></div><h2 class="section-title">Overview</h2><div class="grid"><div class="card"><div class="stat-label">Total Income</div><div class="stat-value">${money(income)}</div><div class="stat-note">All recorded income</div></div><div class="card"><div class="stat-label">Total Expenses</div><div class="stat-value">${money(expense)}</div><div class="stat-note">All recorded expenses</div></div><div class="card"><div class="stat-label">Students</div><div class="stat-value">${state.students.length}</div><div class="stat-note">Student profiles</div></div><div class="card"><div class="stat-label">Fee Due</div><div class="stat-value">${money(due)}</div><div class="stat-note">Outstanding amount</div></div></div><h2 class="section-title">Modules</h2><div class="module-grid"><button class="card module-card" onclick="navigate('transactions')"><div><h3>Financial Management</h3><p>Income, expenses, transaction history and today's totals.</p></div><div class="module-icon">৳</div></button><button class="card module-card" onclick="navigate('students')"><div><h3>Student Management</h3><p>Student profiles, fee collection and outstanding dues.</p></div><div class="module-icon">♙</div></button><button class="card module-card" onclick="navigate('teachers')"><div><h3>Teacher Management</h3><p>Teacher profiles, status and contact information.</p></div><div class="module-icon">♟</div></button><button class="card module-card" onclick="navigate('accounts')"><div><h3>Accounts Overview</h3><p>Income, expenses, balance and outstanding student fees.</p></div><div class="module-icon">৳</div></button></div>`}
function renderTransactions(){content.innerHTML=`<div class="page-head"><div><h2>Income / Expenses</h2><p>Enter, review, edit and delete financial transactions.</p></div><button class="btn btn-primary" onclick="openTransactionModal()">+ New Transaction</button></div><div class="toolbar"><input class="input" id="transactionSearch" placeholder="Search category or description..." oninput="filterTransactions()"><select class="select" id="transactionFilter" onchange="filterTransactions()"><option>All</option><option>Income</option><option>Expense</option></select><input class="input" id="transactionDate" type="date" onchange="filterTransactions()"></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Amount</th><th>Action</th></tr></thead><tbody id="transactionRows"></tbody></table></div></div>`;filterTransactions()}
function filterTransactions(){const q=($("transactionSearch")?.value||"").toLowerCase(),f=$("transactionFilter")?.value||"All",d=$("transactionDate")?.value||"",rows=state.transactions.filter(x=>(f==="All"||x.type===f)&&(!d||x.date===d)&&`${x.category||""} ${x.description||""}`.toLowerCase().includes(q));$("transactionRows").innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.date)}</td><td><span class="badge ${String(x.type||"").toLowerCase()}">${esc(x.type)}</span></td><td>${esc(x.category)}</td><td>${esc(x.description)||"—"}</td><td><strong>${money(x.amount)}</strong></td><td><button class="table-action" onclick="editTransaction('${x.id}')">Edit</button><button class="table-action danger" onclick="deleteTransaction('${x.id}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="6"><div class="empty"><strong>No transactions found</strong>Add a transaction or change the filters.</div></td></tr>`}
function openTransactionModal(id){const x=state.transactions.find(a=>a.id===id)||{type:"Income",date:today(),category:"",amount:"",description:""};openModal(`<div class="modal-head"><h3>${id?"Edit":"New"} Transaction</h3><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveTransaction(event,'${id||""}')"><div class="form-grid"><div class="field"><label>Type</label><select class="select" name="type"><option ${x.type==="Income"?"selected":""}>Income</option><option ${x.type==="Expense"?"selected":""}>Expense</option></select></div><div class="field"><label>Date</label><input class="input" type="date" name="date" value="${esc(x.date)}" required></div><div class="field"><label>Category</label><input class="input" name="category" value="${esc(x.category)}" required></div><div class="field"><label>Amount</label><input class="input" type="number" min="0.01" step="0.01" name="amount" value="${x.amount}" required></div><div class="field full"><label>Description</label><input class="input" name="description" value="${esc(x.description)}"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary">Save Transaction</button></div></form>`)}
function saveTransaction(e,id){e.preventDefault();const x=Object.fromEntries(new FormData(e.target));x.amount=Number(x.amount);if(id){const i=state.transactions.findIndex(a=>a.id===id);if(i>=0)state.transactions[i]={...state.transactions[i],...x}}else state.transactions.unshift({id:uid(),...x});persist();closeModal();render()}
function editTransaction(id){openTransactionModal(id)}
function deleteTransaction(id){if(confirm("Delete this transaction?")){state.transactions=state.transactions.filter(x=>x.id!==id);persist();render()}}
function renderDaily(){const list=state.transactions.filter(x=>x.date===today()),income=list.filter(x=>x.type==="Income").reduce((a,x)=>a+Number(x.amount||0),0),expense=list.filter(x=>x.type==="Expense").reduce((a,x)=>a+Number(x.amount||0),0);content.innerHTML=`<div class="page-head"><div><h2>Today's Total</h2><p>Daily summary for ${new Date().toLocaleDateString("en-IN")}</p></div></div><div class="summary-grid"><div class="card summary-card"><div class="stat-label">Today's Income</div><div class="big">${money(income)}</div></div><div class="card summary-card"><div class="stat-label">Today's Expenses</div><div class="big">${money(expense)}</div></div><div class="card summary-card"><div class="stat-label">Today's Balance</div><div class="big">${money(income-expense)}</div></div></div><h2 class="section-title">Today's Transactions</h2><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Type</th><th>Category</th><th>Description</th><th>Amount</th><th>Action</th></tr></thead><tbody>${list.length?list.map(x=>`<tr><td><span class="badge ${String(x.type||"").toLowerCase()}">${esc(x.type)}</span></td><td>${esc(x.category)}</td><td>${esc(x.description)||"—"}</td><td><strong>${money(x.amount)}</strong></td><td><button class="table-action" onclick="editTransaction('${x.id}')">Edit</button></td></tr>`).join(""):`<tr><td colspan="5"><div class="empty"><strong>No transactions today</strong>Today's financial summary is empty.</div></td></tr>`}</tbody></table></div></div>`}
function renderStudents(){content.innerHTML=`<div class="page-head"><div><h2>Students Data</h2><p>Student profiles and information.</p></div><button class="btn btn-primary" onclick="openStudentModal()">+ Add Student</button></div><div class="toolbar"><input class="input" id="studentSearch" placeholder="Search name, class, guardian..." oninput="filterStudents()"></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Name</th><th>Class</th><th>Guardian</th><th>Phone</th><th>Status</th><th>Action</th></tr></thead><tbody id="studentRows"></tbody></table></div></div>`;filterStudents()}
function filterStudents(){const q=($("studentSearch")?.value||"").toLowerCase(),rows=state.students.filter(x=>`${x.name||""} ${x.className||""} ${x.guardian||""} ${x.phone||""}`.toLowerCase().includes(q));$("studentRows").innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.className)}</td><td>${esc(x.guardian)||"—"}</td><td>${esc(x.phone)||"—"}</td><td><span class="badge paid">Active</span></td><td><button class="table-action" onclick="viewStudent('${x.id}')">View</button><button class="table-action" onclick="openStudentModal('${x.id}')">Edit</button><button class="table-action danger" onclick="deleteStudent('${x.id}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="6"><div class="empty"><strong>No students found</strong>Add a student profile to begin.</div></td></tr>`}
function openStudentModal(id){const x=state.students.find(a=>a.id===id)||{name:"",className:"",guardian:"",phone:"",address:"",notes:""};openModal(`<div class="modal-head"><h3>${id?"Edit":"Add"} Student</h3><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveStudent(event,'${id||""}')"><div class="form-grid"><div class="field full"><label>Student Name</label><input class="input" name="name" value="${esc(x.name)}" required></div><div class="field"><label>Class</label><input class="input" name="className" value="${esc(x.className)}" required></div><div class="field"><label>Guardian</label><input class="input" name="guardian" value="${esc(x.guardian)}"></div><div class="field"><label>Phone</label><input class="input" name="phone" value="${esc(x.phone)}" inputmode="tel"></div><div class="field"><label>Address</label><input class="input" name="address" value="${esc(x.address)}"></div><div class="field full"><label>Notes</label><input class="input" name="notes" value="${esc(x.notes)}"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary">Save Student</button></div></form>`)}
function saveStudent(e,id){e.preventDefault();const x=Object.fromEntries(new FormData(e.target));if(id){const i=state.students.findIndex(a=>a.id===id);if(i>=0)state.students[i]={...state.students[i],...x}}else state.students.unshift({id:uid(),...x});persist();closeModal();render()}
function viewStudent(id){const x=state.students.find(a=>a.id===id);if(!x)return;const fees=state.fees.filter(f=>f.studentId===id),due=fees.reduce((a,f)=>a+Number(f.due||0),0);openModal(`<div class="modal-head"><h3>Student Profile</h3><button class="close" onclick="closeModal()">×</button></div><div class="profile"><div><b>Name</b><span>${esc(x.name)}</span></div><div><b>Class</b><span>${esc(x.className)}</span></div><div><b>Guardian</b><span>${esc(x.guardian)||"—"}</span></div><div><b>Phone</b><span>${esc(x.phone)||"—"}</span></div><div><b>Address</b><span>${esc(x.address)||"—"}</span></div><div><b>Fee Due</b><span>${money(due)}</span></div><div class="profile-notes"><b>Notes</b><span>${esc(x.notes)||"—"}</span></div></div><div class="modal-actions"><button class="btn btn-light" onclick="closeModal()">Close</button><button class="btn btn-primary" onclick="closeModal();openStudentModal('${x.id}')">Edit Profile</button></div>`)}
function deleteStudent(id){if(confirm("Delete this student and related fee records?")){state.students=state.students.filter(x=>x.id!==id);state.fees=state.fees.filter(x=>x.studentId!==id);persist();render()}}
render();