const state={students:JSON.parse(localStorage.getItem('dh_students')||'[]'),fees:JSON.parse(localStorage.getItem('dh_fees')||'[]'),income:JSON.parse(localStorage.getItem('dh_income')||'[]'),expense:JSON.parse(localStorage.getItem('dh_expense')||'[]')};
const save=k=>localStorage.setItem(`dh_${k}`,JSON.stringify(state[k]));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const emptyRow=(cols,text='কোনো তথ্য নেই')=>`<tr><td colspan="${cols}" class="status-empty">${text}</td></tr>`;
function renderStudents(){const q=(document.querySelector('#student-search')?.value||'').toLowerCase().trim();const rows=state.students.filter(s=>[s.id,s.name,s.phone,s.className,s.guardian,s.type].join(' ').toLowerCase().includes(q));document.querySelector('#student-total').textContent=state.students.length;document.querySelector('#student-general').textContent=state.students.filter(s=>s.type!=='Orphan').length;document.querySelector('#student-orphan').textContent=state.students.filter(s=>s.type==='Orphan').length;document.querySelector('#student-count').textContent=`${rows.length} Students`;document.querySelector('#student-table').innerHTML=rows.length?rows.map(s=>`<tr><td><b>${esc(s.id)}</b></td><td>${esc(s.name)}</td><td>${esc(s.className)}</td><td>${esc(s.guardian)||'—'}</td><td>${esc(s.phone)||'—'}</td><td><span class="badge ${s.type==='Orphan'?'orphan':''}">${esc(s.type||'General')}</span></td><td><button class="small-btn" data-edit-student="${esc(s.id)}">Edit</button><button class="small-btn danger-btn" data-delete-student="${esc(s.id)}">Delete</button></td></tr>`).join(''):emptyRow(7);}
function renderFees(){const q=(document.querySelector('#fee-search')?.value||'').toLowerCase();const rows=state.fees.filter(f=>[f.student,f.month].join(' ').toLowerCase().includes(q));document.querySelector('#fee-count').textContent=`${rows.length} Records`;document.querySelector('#fee-table').innerHTML=rows.length?rows.map(f=>`<tr><td>${esc(f.student)}</td><td>${esc(f.month)}</td><td>₹${Number(f.fee).toLocaleString('en-IN')}</td><td>₹${Number(f.paid).toLocaleString('en-IN')}</td><td>₹${Math.max(0,f.fee-f.paid).toLocaleString('en-IN')}</td><td><span class="badge">${f.paid>=f.fee?'Paid':'Due'}</span></td></tr>`).join(''):emptyRow(6);}
function renderMoney(type){const q=(document.querySelector(`#${type}-search`)?.value||'').toLowerCase();const rows=state[type].filter(x=>[x.category,x.description].join(' ').toLowerCase().includes(q));const total=rows.reduce((a,x)=>a+Number(x.amount||0),0);document.querySelector(`#${type}-total`).textContent=`Total: ₹${total.toLocaleString('en-IN')}`;document.querySelector(`#${type}-table`).innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.description)||'—'}</td><td>₹${Number(x.amount).toLocaleString('en-IN')}</td></tr>`).join(''):emptyRow(4);}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active-page',p.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));}
function openStudent(id=null){const s=id?state.students.find(x=>x.id===id):null;document.querySelector('#student-modal-title').textContent=s?'Edit Student':'Add Student';document.querySelector('#student-edit-id').value=s?.id||'';document.querySelector('#form-id').value=s?.id||`ST-${String(state.students.length+1).padStart(3,'0')}`;document.querySelector('#form-name').value=s?.name||'';document.querySelector('#form-class').value=s?.className||'';document.querySelector('#form-guardian').value=s?.guardian||'';document.querySelector('#form-phone').value=s?.phone||'';document.querySelector('#form-type').value=s?.type||'General';document.querySelector('#form-admission').value=s?.admissionDate||'';document.querySelector('#form-address').value=s?.address||'';document.querySelector('#student-modal').classList.add('open');document.querySelector('#student-modal').setAttribute('aria-hidden','false');}
function closeStudent(){document.querySelector('#student-modal').classList.remove('open');document.querySelector('#student-modal').setAttribute('aria-hidden','true');}
function addFee(){const student=prompt('Student ID / নাম:');if(!student)return;const month=prompt('মাস:')||'';const fee=Number(prompt('মোট ফি:',0));const paid=Number(prompt('Paid:',0));if(!Number.isFinite(fee)||fee<0||!Number.isFinite(paid)||paid<0)return alert('সঠিক amount দিন।');state.fees.push({student,month,fee,paid});save('fees');renderFees();}
function addMoney(type){const amount=Number(prompt(type==='income'?'আয়ের Amount:':'ব্যয়ের Amount:',0));if(!amount||amount<0)return;state[type].push({date:new Date().toISOString().slice(0,10),category:prompt('খাত:')||'অন্যান্য',description:prompt('বিবরণ:')||'',amount});save(type);renderMoney(type);}
function toggleLogoMenu(force){const menu=document.querySelector('#logo-menu');menu.classList.toggle('open',force??!menu.classList.contains('open'));}
function loadLogo(){const data=localStorage.getItem('dh_logo');const holder=document.querySelector('#logo-placeholder');if(data){holder.outerHTML=`<img id="custom-logo" src="${data}" alt="Madrasa Logo">`; }else if(!document.querySelector('#logo-placeholder')){document.querySelector('#custom-logo').outerHTML='<span id="logo-placeholder">DH</span>';}}
function addLogo(){document.querySelector('#logo-input').click();toggleLogoMenu(false);}
function removeLogo(){localStorage.removeItem('dh_logo');document.querySelector('#custom-logo')?.remove();if(!document.querySelector('#logo-placeholder'))document.querySelector('#logo-button').insertAdjacentHTML('afterbegin','<span id="logo-placeholder">DH</span>');toggleLogoMenu(false);}
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav)showPage(nav.dataset.page);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='open-student')openStudent();if(action==='close-student')closeStudent();if(action==='add-fee')addFee();if(action==='add-income')addMoney('income');if(action==='add-expense')addMoney('expense');const edit=e.target.closest('[data-edit-student]');if(edit)openStudent(edit.dataset.editStudent);const del=e.target.closest('[data-delete-student]');if(del&&confirm('এই ছাত্রের তথ্য Delete করবেন?')){state.students=state.students.filter(s=>s.id!==del.dataset.deleteStudent);save('students');renderStudents();}if(e.target.id==='logo-button'){toggleLogoMenu();}else if(!e.target.closest('.logo-picker'))toggleLogoMenu(false);if(e.target.id==='add-logo')addLogo();if(e.target.id==='remove-logo')removeLogo();});
document.querySelector('#logo-input').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return alert('শুধু image file দিন।');const reader=new FileReader();reader.onload=()=>{localStorage.setItem('dh_logo',reader.result);loadLogo();};reader.readAsDataURL(file);e.target.value='';});
document.querySelector('#student-form').addEventListener('submit',e=>{e.preventDefault();const original=document.querySelector('#student-edit-id').value;const data={id:document.querySelector('#form-id').value.trim(),name:document.querySelector('#form-name').value.trim(),className:document.querySelector('#form-class').value.trim(),guardian:document.querySelector('#form-guardian').value.trim(),phone:document.querySelector('#form-phone').value.trim(),type:document.querySelector('#form-type').value,admissionDate:document.querySelector('#form-admission').value,address:document.querySelector('#form-address').value.trim()};if(!data.id||!data.name||!data.className)return alert('Student ID, নাম ও শ্রেণি আবশ্যক।');if(state.students.some(s=>s.id===data.id&&s.id!==original))return alert('এই Student ID ইতিমধ্যে আছে।');if(original){const i=state.students.findIndex(s=>s.id===original);if(i>-1)state.students[i]=data;}else state.students.push(data);save('students');closeStudent();renderStudents();});
['student-search','fee-search','income-search','expense-search'].forEach(id=>document.getElementById(id)?.addEventListener('input',()=>id==='student-search'?renderStudents():id==='fee-search'?renderFees():renderMoney(id.split('-')[0])));
document.querySelector('#student-modal').addEventListener('click',e=>{if(e.target.id==='student-modal')closeStudent();});
loadLogo();renderStudents();renderFees();renderMoney('income');renderMoney('expense');
