const KEY='dingel_hafizia_students_v1';
const PAY_KEY='dingel_hafizia_payments_v1';
let students=JSON.parse(localStorage.getItem(KEY)||'[]');
let payments=JSON.parse(localStorage.getItem(PAY_KEY)||'[]');
let currentStudentId=null;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem(KEY,JSON.stringify(students));localStorage.setItem(PAY_KEY,JSON.stringify(payments));}
function esc(v=''){return String(v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function money(v){return Number(v||0).toFixed(2);}
function login(){if($('#username').value.trim()==='admin'&&$('#password').value==='admin123'){sessionStorage.setItem('dh_login','1');boot();}else alert('Username অথবা password ভুল।');}
function logout(){sessionStorage.removeItem('dh_login');location.reload();}
function boot(){if(sessionStorage.getItem('dh_login')!=='1')return;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');show('dashboard');}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(`#page-${page}`).classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===page));if(page==='students')renderStudents();if(page==='fees')renderFees();}
function addStudent(){currentStudentId=null;$('#studentModalTitle').textContent='Add Student';$('#studentForm').reset();$('#studentCategory').value='Paid';$('#studentClass').value='Maktab';$('#studentStatus').value='Active';$('#studentModal').showModal();}
function editStudent(id){const s=students.find(x=>x.id===id);if(!s)return;currentStudentId=id;$('#studentModalTitle').textContent='Edit Student';Object.entries({studentRoll:s.roll,studentName:s.name,fatherName:s.father,address:s.address,studentAadhaar:s.studentAadhaar,fatherAadhaar:s.fatherAadhaar,phone:s.phone,admissionFees:s.admissionFees,monthlyFees:s.monthlyFees,admissionDate:s.admissionDate,studentCategory:s.category,studentClass:s.className,studentStatus:s.status}).forEach(([k,v])=>{if($('#'+k))$('#'+k).value=v??''});$('#studentModal').showModal();}
function saveStudent(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());if(!d.studentRoll||!d.studentName||!d.fatherName){alert('Roll, Student Name এবং Father Name অবশ্যই দিতে হবে।');return;}if(d.studentCategory==='Atim'||d.studentCategory==='Free')d.monthlyFees='0';const obj={id:currentStudentId||Date.now(),roll:d.studentRoll,name:d.studentName,father:d.fatherName,address:d.address,studentAadhaar:d.studentAadhaar,fatherAadhaar:d.fatherAadhaar,phone:d.phone,admissionFees:Number(d.admissionFees||0),monthlyFees:Number(d.monthlyFees||0),admissionDate:d.admissionDate,category:d.studentCategory,className:d.studentClass,status:d.studentStatus};if(currentStudentId)students=students.map(x=>x.id===currentStudentId?obj:x);else students.push(obj);save();$('#studentModal').close();renderStudents();}
function deleteStudent(id){if(!confirm('এই student-কে delete করতে চান?'))return;students=students.filter(x=>x.id!==id);payments=payments.filter(x=>x.studentId!==id);save();renderStudents();}
function viewStudent(id){const s=students.find(x=>x.id===id);if(!s)return;currentStudentId=id;const paid=payments.filter(p=>p.studentId===id).reduce((a,p)=>a+Number(p.amount),0);const due=Math.max(Number(s.monthlyFees)-paid,0);$('#details').innerHTML=`<div class="details-header"><div><h2>${esc(s.name)}</h2><p>Roll: ${esc(s.roll)} · ${esc(s.className)} · ${esc(s.category)}</p></div><span class="status ${s.status.toLowerCase()}">${esc(s.status)}</span></div><div class="detail-grid">${[['ID',s.id],['Roll',s.roll],['Student Name',s.name],['Father Name',s.father],['Address',s.address],['Student Aadhaar',s.studentAadhaar],['Father Aadhaar',s.fatherAadhaar],['Phone',s.phone],['Admission Fees',money(s.admissionFees)],['Monthly Fees',money(s.monthlyFees)],['Total Paid',money(paid)],['Current Due',money(due)],['Admission Date',s.admissionDate],['Category',s.category],['Class',s.className],['Status',s.status]].map(([a,b])=>`<div><b>${a}</b><span>${esc(b??'')}</span></div>`).join('')}</div><div class="modal-actions"><button onclick="history(${s.id});$('#detailsModal').close()">Payment History</button><button onclick="editStudent(${s.id});$('#detailsModal').close()">Edit Student</button></div>`;$('#detailsModal').showModal();}
function renderStudents(){const q=($('#studentSearch')?.value||'').toLowerCase();const status=$('#studentFilter')?.value||'All';const rows=students.filter(s=>(!q||[s.roll,s.name,s.father,s.phone].join(' ').toLowerCase().includes(q))&&(status==='All'||s.status===status));$('#studentCount').textContent=students.length;$('#studentRows').innerHTML=rows.map(s=>`<tr><td>${esc(s.roll)}</td><td>${esc(s.name)}</td><td>${esc(s.father)}</td><td>${esc(s.className)}</td><td>${esc(s.category)}</td><td>${money(s.monthlyFees)}</td><td><span class="status ${s.status.toLowerCase()}">${s.status}</span></td><td><button onclick="viewStudent(${s.id})">View</button> <button onclick="editStudent(${s.id})">Edit</button> <button class="danger" onclick="deleteStudent(${s.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No students found</td></tr>';}
function addPayment(){const active=students.filter(s=>s.status==='Active');if(!active.length){alert('প্রথমে Active student add করুন।');return;}$('#paymentStudent').innerHTML=active.map(s=>`<option value="${s.id}">${esc(s.roll)} - ${esc(s.name)}</option>`).join('');$('#paymentForm').reset();$('#paymentStudent').value=active[0].id;$('#paymentModal').showModal();}
function savePayment(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());if(!d.paymentStudent||!d.paymentMonth||!d.amount||!d.paymentDate){alert('Student, month, amount এবং date দিন।');return;}payments.push({id:Date.now(),studentId:Number(d.paymentStudent),month:d.paymentMonth,amount:Number(d.amount),date:d.paymentDate,note:d.note||''});save();$('#paymentModal').close();renderFees();}
function history(id){const s=students.find(x=>x.id===id);if(!s)return;const list=payments.filter(p=>p.studentId===id).sort((a,b)=>b.date.localeCompare(a.date));$('#history').innerHTML=`<h2>Payment History — ${esc(s.name)}</h2><table><thead><tr><th>Month</th><th>Amount</th><th>Date</th><th>Note</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td>${esc(p.month)}</td><td>${money(p.amount)}</td><td>${esc(p.date)}</td><td>${esc(p.note)}</td><td><button class="danger" onclick="deletePayment(${p.id},${id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No payment history</td></tr>'}</tbody></table>`;$('#historyModal').showModal();}
function deletePayment(pid,sid){if(!confirm('Payment record delete করতে চান?'))return;payments=payments.filter(p=>p.id!==pid);save();history(sid);renderFees();}
function renderFees(){const q=($('#feeSearch')?.value||'').toLowerCase();const rows=students.filter(s=>!q||[s.roll,s.name,s.father].join(' ').toLowerCase().includes(q));$('#feeRows').innerHTML=rows.map(s=>{const paid=payments.filter(p=>p.studentId===s.id).reduce((a,p)=>a+Number(p.amount),0);const due=Math.max(Number(s.monthlyFees)-paid,0);return `<tr><td>${esc(s.roll)}</td><td>${esc(s.name)}</td><td>${money(s.monthlyFees)}</td><td>${money(paid)}</td><td>${money(due)}</td><td><button onclick="addPaymentFor(${s.id})">Add Payment</button> <button onclick="history(${s.id})">History</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No students found</td></tr>';}
function addPaymentFor(id){addPayment();$('#paymentStudent').value=id;}
document.addEventListener('DOMContentLoaded',()=>{boot();$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login()});$('#studentForm').addEventListener('submit',saveStudent);$('#paymentForm').addEventListener('submit',savePayment);$('#studentSearch').addEventListener('input',renderStudents);$('#studentFilter').addEventListener('change',renderStudents);$('#feeSearch').addEventListener('input',renderFees);document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));});
