// Firebase Authentication integration.
(function(){
  const LOGIN_ERROR={'auth/invalid-email':'Invalid email address.','auth/user-disabled':'This account has been disabled.','auth/user-not-found':'No account found with this email.','auth/wrong-password':'Incorrect password.','auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'This email is already registered.','auth/weak-password':'Password is too weak. Use at least 6 characters.','auth/too-many-requests':'Too many attempts. Please try again later.','auth/network-request-failed':'Network connection failed. Please try again.','auth/requires-recent-login':'For security, please sign in again and then change the password.'};
  let profile=null;let resolveAuthReady;window.dhAuthReady=new Promise(resolve=>{resolveAuthReady=resolve});window.dhRole='Teacher';window.dhProfile=null;
  const ROLE_PERMISSIONS={Admin:['dashboard','students','fees','accounts','reports','settings'],Teacher:['dashboard','students','fees','reports','settings']};
  function normalizeRole(value){const r=String(value||'').trim().toLowerCase();return r==='admin'?'Admin':'Teacher'}
  function can(page){return (ROLE_PERMISSIONS[window.dhRole]||[]).includes(page)}window.dhCan=can;
  function applyRoleUI(){document.querySelectorAll('.nav-btn[data-page]').forEach(btn=>{btn.style.display=can(btn.dataset.page)?'':''});document.querySelectorAll('[data-admin-only]').forEach(el=>el.style.display=window.dhRole==='Admin'?'':'none');const label=document.querySelector('#userRole');if(label)label.textContent=window.dhRole}
  async function loadProfile(user){try{const snap=await firebase.firestore().collection('users').doc(user.uid).get();if(snap.exists){profile=snap.data();profile.role=normalizeRole(profile.role)}else{profile={role:'Teacher',name:user.email||'Teacher',email:user.email||'',createdAt:firebase.firestore.FieldValue.serverTimestamp()};try{await firebase.firestore().collection('users').doc(user.uid).set(profile,{merge:true})}catch(e){console.warn('Could not create profile',e)}}window.dhProfile=profile;window.dhRole=normalizeRole(profile.role);applyRoleUI()}catch(e){console.error('Profile load failed',e);window.dhRole='Teacher';applyRoleUI()}}
  function setLoading(loading){const b=document.querySelector('#loginForm button[type="submit"]');if(b){b.disabled=loading;b.textContent=loading?'SIGNING IN...':'LOGIN'}}
  window.login=async function(){const email=document.querySelector('#username').value.trim(),password=document.querySelector('#password').value;if(!email||!password)return;setLoading(true);try{await dhAuth.signInWithEmailAndPassword(email,password)}catch(e){alert(LOGIN_ERROR[e.code]||e.message||'Login failed. Please try again.')}finally{setLoading(false)}};
  window.logout=async function(){try{await dhAuth.signOut()}catch(e){alert(e.message||'Logout failed. Please try again.')}};window.boot=function(){};
  window.openTeacherModal=function(){if(window.dhRole!=='Admin'){alert('Only Admin can create a Teacher account.');return}document.querySelector('#teacherForm')?.reset();document.querySelector('#teacherModal')?.showModal()};
  window.createTeacherAccount=async function(){if(window.dhRole!=='Admin'){alert('Only Admin can create a Teacher account.');return}const name=document.querySelector('#teacherName')?.value.trim(),email=document.querySelector('#teacherEmail')?.value.trim().toLowerCase(),password=document.querySelector('#teacherPassword')?.value,confirm=document.querySelector('#teacherPasswordConfirm')?.value;if(!name||!email||!password||!confirm){alert('Please fill all fields.');return}if(password.length<6){alert('Password must be at least 6 characters.');return}if(password!==confirm){alert('Passwords do not match.');return}const btn=document.querySelector('#createTeacherBtn');if(btn){btn.disabled=true;btn.textContent='Creating...'}let secondary=null;try{secondary=firebase.apps.find(a=>a.name==='teacherCreator');if(!secondary)secondary=await firebase.initializeApp(firebaseConfig,'teacherCreator');const secondaryAuth=secondary.auth();const cred=await secondaryAuth.createUserWithEmailAndPassword(email,password);await firebase.firestore().collection('users').doc(cred.user.uid).set({name,email,role:'Teacher',status:'Active',createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:dhAuth.currentUser.uid},{merge:true});await secondaryAuth.signOut();document.querySelector('#teacherForm')?.reset();document.querySelector('#teacherModal')?.close();alert('Teacher account created successfully.\n\nEmail: '+email+'\nPassword: '+password+'\n\nTeacher can now login from the normal login screen.')}catch(e){alert(LOGIN_ERROR[e.code]||e.message||'Could not create Teacher account.')}finally{if(btn){btn.disabled=false;btn.textContent='Create Teacher'}}};
  window.changePassword=async function(){const user=dhAuth.currentUser;if(!user){alert('Please login first.');return}if(window.dhRole!=='Admin'){alert('Only Admin can change the login password.');return}const current=document.querySelector('#currentPassword')?.value||'',next=document.querySelector('#newPassword')?.value||'',confirm=document.querySelector('#confirmPassword')?.value||'';if(!current||!next||!confirm){alert('Please fill all password fields.');return}if(next.length<6){alert('New password must be at least 6 characters.');return}if(next!==confirm){alert('New password and confirmation do not match.');return}if(current===next){alert('New password must be different from the current password.');return}try{const credential=firebase.auth.EmailAuthProvider.credential(user.email,current);await user.reauthenticateWithCredential(credential);await user.updatePassword(next);document.querySelector('#changePasswordForm')?.reset();document.querySelector('#passwordModal')?.close();alert('Password changed successfully.')}catch(e){const msg=e.code==='auth/wrong-password'||e.code==='auth/invalid-credential'?'Current password is incorrect.':(LOGIN_ERROR[e.code]||e.message||'Could not change password.');alert(msg)}};
  window.openPasswordModal=function(){if(window.dhRole!=='Admin'){alert('Only Admin can access Change Password.');return}document.querySelector('#passwordModal')?.showModal()};
  window.loadMadrasaLogo=async function(){try{const user=dhAuth.currentUser;if(!user)return;const snap=await firebase.firestore().collection('users').doc(user.uid).get();const url=snap.exists?snap.data().logoUrl:'';document.querySelectorAll('[data-madrasa-logo]').forEach(img=>{if(url){img.src=url;img.style.display='block'}else img.style.display='none'})}catch(e){console.warn('Logo load failed',e)}};
  window.uploadMadrasaLogo=async function(){if(window.dhRole!=='Admin'){alert('Only Admin can change the logo.');return}const input=document.querySelector('#madrasaLogo'),file=input?.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){alert('Please select an image file.');return}if(file.size>5*1024*1024){alert('Logo must be smaller than 5 MB.');return}const btn=document.querySelector('#logoUploadBtn');if(btn){btn.disabled=true;btn.textContent='Uploading...'}try{const ref=firebase.storage().ref('studentPhotos/_settings/madrasa-logo');await ref.put(file,{contentType:file.type,cacheControl:'public,max-age=3600'});const url=await ref.getDownloadURL();await firebase.firestore().collection('users').doc(dhAuth.currentUser.uid).set({logoUrl:url,logoUpdatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await window.loadMadrasaLogo();alert('Madrasa logo updated successfully.');input.value=''}catch(e){alert(e.message||'Logo upload failed.')}finally{if(btn){btn.disabled=false;btn.textContent='Upload Logo'}}};
  document.addEventListener('DOMContentLoaded',function(){const login=document.querySelector('#login'),app=document.querySelector('#app'),form=document.querySelector('#loginForm');app.classList.add('hidden');if(form)form.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();window.login()},true);document.querySelectorAll('.nav-btn[data-page]').forEach(btn=>btn.addEventListener('click',function(e){if(!can(btn.dataset.page)){e.preventDefault();return}if(window.show)window.show(btn.dataset.page)},false));const username=document.querySelector('#username'),label=username?.closest('.field')?.querySelector('label');if(label)label.textContent='Email';if(username){username.type='email';username.autocomplete='email';username.placeholder='admin@example.com'}document.querySelector('#teacherForm')?.addEventListener('submit',function(e){e.preventDefault();window.createTeacherAccount()});document.querySelector('#changePasswordForm')?.addEventListener('submit',function(e){e.preventDefault();window.changePassword()});document.querySelector('#logoUploadBtn')?.addEventListener('click',function(){window.uploadMadrasaLogo()});let resolved=false;try{dhAuth.onAuthStateChanged(async function(user){resolved=true;document.body.classList.add('auth-ready');if(user){await loadProfile(user);resolveAuthReady(user);login.classList.add('hidden');app.classList.remove('hidden');if(window.show)window.show('dashboard');const su=document.querySelector('#signedInUser');if(su)su.textContent='Signed in: '+(user.email||'')+' | Role: '+window.dhRole;if(window.loadMadrasaLogo)window.loadMadrasaLogo()}else{app.classList.add('hidden');login.classList.remove('hidden');resolveAuthReady(null);const p=document.querySelector('#password');if(p)p.value=''}})}catch(e){console.error('Firebase Auth initialization failed:',e);app.classList.add('hidden');login.classList.remove('hidden')}setTimeout(function(){if(!resolved){app.classList.add('hidden');login.classList.remove('hidden')}},5000)});
})();
