const express=require('express');
const mongoose=require('mongoose');
const cors=require('cors');
require('dotenv').config();
const studentRoutes=require('./routes/studentRoutes');
const transactionRoutes=require('./routes/transactionRoutes');
const app=express();
app.use(cors());
app.use(express.json());
app.get('/api/health',(req,res)=>res.json({ok:true,app:'Dingel Hafizia App'}));
app.use('/api/students',studentRoutes);
app.use('/api/transactions',transactionRoutes);
const PORT=process.env.PORT||5000;
const MONGO_URI=process.env.MONGO_URI||'mongodb://localhost:27017/dingelHafiziaDB';
mongoose.connect(MONGO_URI).then(()=>{console.log('MongoDB connected');app.listen(PORT,()=>console.log(`Server running on http://localhost:${PORT}`));}).catch(err=>{console.error('MongoDB connection failed:',err.message);process.exit(1);});