/* Dingel Hafizia App — Financial Reports */
(function(){
  const money=n=>{let c='₹';try{c=getAppSettings().currency||'₹'}catch(e){}return c+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})};
  const escx=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let range='month';
  const iso=d=>{const x=new Date(d);return isNaN(x)?'':x.toISOString().slice(0,10)};
  const bounds=()=>{const now=new Date(), today=iso(now);if(range==='today')return [today,today];if(range==='year')return [`${now.getFullYear()}-01-01`,`${now.getFullYear()}-12-31`];const y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),last=new Date(y,now.getMonth()+1,0).getDate();return [`${y}-${m}-01`,`${y}-${m}-${String(last).padStart(2,'0')}`]};
  window.renderFinancialReports=function(){
    if(typeof canAccess==='function'&&!canAccess('transactions')){content.innerHTML='<div class="card empty"><strong>Access denied</strong><span>You do not have permission to view financial reports.</span></div>';return}
    const [from,to]=bounds(), tx=Array.isArray(state.transactions)?state.transactions:[], rows=tx.filter(x=>{const d=iso(x.date);return d&&d>=from&&d<=to});
    const sum=t=>rows.filter(x=>x.type===t).reduce((s,x)=>s+Number(x.amount||0),0),inc=sum('Income'),exp=sum('Expense'),bal=inc-exp;
    const cats={};rows.forEach(x=>{const k=(x.category||'Other')+'|'+x.type;cats[k]=(cats[k]||0)+Number(x.amount||0)});
    const top=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,12);
    const button=(v,label)=>`<button class="fr-filter ${range===v?'active':''}" onclick="setFinancialReportRange('${v}')">${label}</button>`;
    content.innerHTML=`<div class="page-head"><div><h2>Financial Reports</h2><p>Income, expense and category-wise financial summary.</p></div></div><div class="card fr-card"><div class="fr-head"><div><strong>Report Period</strong><small>${from} → ${to}</small></div><div class="fr-filters">${button('today','Today')}${button('month','This Month')}${button('year','This Year')}</div></div></div><div class="summary-grid fr-summary"><div class="card summary-card"><div class="stat-label">INCOME</div><div class="big">${money(inc)}</div></div><div class="card summary-card"><div class="stat-label">EXPENSE</div><div class="big">${money(exp)}</div></div><div class="card summary-card"><div class="stat-label">NET BALANCE</div><div class="big">${money(bal)}</div></div></div><div class="card fr-card"><div class="fr-head"><div><strong>Category Summary</strong><small>${rows.length} transaction${rows.length===1?'':'s'}</small></div></div><div class="fr-list">${top.length?top.map(([key,v])=>{const [name,type]=key.split('|');return `<div class="fr-row"><span><span class="fr-badge ${type==='Income'?'income':'expense'}">${type}</span> ${escx(name)}</span><strong>${money(v)}</strong></div>`}).join(''):'<div class="empty"><strong>No data yet</strong><span>Add transactions to generate this report.</span></div>'}</div></div><div class="card fr-card"><div class="fr-head"><div><strong>Quick Actions</strong><small>Manage your financial records</small></div></div><div class="fr-actions"><button class="btn btn-light" onclick="renderTransactions()">View Transactions</button><button class="btn btn-primary" onclick="openTransactionModal('','Income')">＋ Add Income</button><button class="btn btn-light" onclick="openTransactionModal('','Expense')">− Add Expense</button></div></div>`;
  };
  window.setFinancialReportRange=function(v){range=v;renderFinancialReports()};
})();
