import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API='http://localhost:5000/api';
const emptyStudent={name:'',rollNo:'',category:'General',guardianName:'',contactNumber:'',address:''};
function App(){
 const [summary,setSummary]=useState({totalIncome:0,totalExpense:0,balance:0});
 const [students,setStudents]=useState([]); const [message,setMessage]=useState(''); const [search,setSearch]=useState('');
 const [editingId,setEditingId]=useState(null); const [studentForm,setStudentForm]=useState(emptyStudent);
 const [form,setForm]=useState({type:'INCOME',category:'Donation',amount:'',donorName:'',description:''});
 const load=async()=>{try{const [s,t]=await Promise.all([fetch(API+'/transactions/summary'),fetch(API+'/students/list')]);if(!s.ok||!t.ok)throw new Error();setSummary(await s.json());setStudents(await t.json());}catch(e){setMessage('Backend চালু আছে কি না যাচাই করুন।')}};
 useEffect(()=>{load()},[]);
 const filteredStudents=useMemo(()=>{const q=search.trim().toLowerCase();return students.filter(s=>!q||String(s.rollNo).includes(q)||s.name.toLowerCase().includes(q)||s.category.toLowerCase().includes(q)||String(s.contactNumber||'').includes(q));},[students,search]);
 const submitTransaction=async e=>{e.preventDefault();setMessage('');try{const r=await fetch(API+'/transactions/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok)throw new Error();setForm({type:'INCOME',category:'Donation',amount:'',donorName:'',description:''});setMessage('লেনদেন সফলভাবে সংরক্ষণ হয়েছে।');load();}catch{setMessage('সংরক্ষণ করা যায়নি। Backend/MongoDB যাচাই করুন।')}};
 const submitStudent=async e=>{e.preventDefault();setMessage('');try{const method=editingId?'PUT':'POST';const url=editingId?`${API}/students/${editingId}`:API+'/students/add';const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...studentForm,rollNo:Number(studentForm.rollNo)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'save');setStudentForm(emptyStudent);setEditingId(null);setMessage(editingId?'ছাত্রের তথ্য আপডেট হয়েছে।':'ছাত্র সফলভাবে যোগ হয়েছে।');load();}catch(e){setMessage(e.message||'ছাত্র সংরক্ষণ করা যায়নি।')}};
 const editStudent=s=>{setEditingId(s._id);setStudentForm({name:s.name||'',rollNo:s.rollNo||'',category:s.category||'General',guardianName:s.guardianName||'',contactNumber:s.contactNumber||'',address:s.address||''});window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});};
 const deleteStudent=async id=>{if(!window.confirm('এই ছাত্রের তথ্য মুছে ফেলতে চান?'))return;try{const r=await fetch(`${API}/students/${id}`,{method:'DELETE'});if(!r.ok)throw new Error();setMessage('ছাত্রের তথ্য মুছে ফেলা হয়েছে।');load();}catch{setMessage('তথ্য মুছে ফেলা যায়নি।')}};
 return <main><header><h1>ডিঙ্গেল হাফিজিয়া মাদ্রাসা</h1><p><b>পরিচালনায়:</b> ডিঙ্গেল ইসমাইল ওয়েলফেয়ার ট্রাস্ট (Govt Regd: IV/120/600051)</p><p>গ্রাম+পোস্ট-ডিঙ্গেল, থানা-কালীগঞ্জ, জেলা-নদীয়া, পিন-৭৪১১৩৭</p><p>মোবাইল: ৯৫৮৬০৭৭৮৩০ / ৮৫৯৭৭৪৬৯৮২</p></header>
 <section className="cards"><div><span>মোট আয়</span><strong>₹ {summary.totalIncome}</strong></div><div><span>মোট ব্যয়</span><strong>₹ {summary.totalExpense}</strong></div><div><span>অবশিষ্ট ফান্ড</span><strong>₹ {summary.balance}</strong></div></section>
 <div className="warning"><b>বিশেষ সতর্কবার্তা:</b> কোনো বাচ্চা ছেলের মাধ্যমে দান তোলা নিষেধ। দান করার আগে সংগ্রাহকের পরিচয়পত্র ও মাদ্রাসার অফিসিয়াল রসিদ যাচাই করে নিন।</div>
 <section className="panel"><h2>ছাত্র ব্যবস্থাপনা / Student Management</h2><form onSubmit={submitStudent}><div className="row"><input required placeholder="ছাত্রের নাম" value={studentForm.name} onChange={e=>setStudentForm({...studentForm,name:e.target.value})}/><input required type="number" min="1" placeholder="রোল নম্বর" value={studentForm.rollNo} onChange={e=>setStudentForm({...studentForm,rollNo:e.target.value})}/></div><div className="row"><select value={studentForm.category} onChange={e=>setStudentForm({...studentForm,category:e.target.value})}><option>General</option><option>Needy</option><option>Orphan</option></select><input placeholder="অভিভাবকের নাম" value={studentForm.guardianName} onChange={e=>setStudentForm({...studentForm,guardianName:e.target.value})}/></div><div className="row"><input placeholder="মোবাইল নম্বর" value={studentForm.contactNumber} onChange={e=>setStudentForm({...studentForm,contactNumber:e.target.value})}/><input placeholder="ঠিকানা" value={studentForm.address} onChange={e=>setStudentForm({...studentForm,address:e.target.value})}/></div><div className="row"><button>{editingId?'আপডেট করুন (Update)':'ছাত্র যোগ করুন (Add Student)'}</button>{editingId&&<button type="button" className="secondary" onClick={()=>{setEditingId(null);setStudentForm(emptyStudent)}}>বাতিল</button>}</div></form></section>
 <section className="panel"><div className="sectionhead"><h2>ছাত্র তালিকা: {students.length} জন</h2><input className="search" placeholder="নাম / রোল / মোবাইল দিয়ে খুঁজুন" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="tablewrap"><table><thead><tr><th>রোল</th><th>নাম</th><th>ক্যাটাগরি</th><th>অভিভাবক</th><th>মোবাইল</th><th>অ্যাকশন</th></tr></thead><tbody>{filteredStudents.map(s=><tr key={s._id}><td>{s.rollNo}</td><td>{s.name}</td><td>{s.category}</td><td>{s.guardianName||'-'}</td><td>{s.contactNumber||'-'}</td><td><button className="small" onClick={()=>editStudent(s)}>Edit</button><button className="small danger" onClick={()=>deleteStudent(s._id)}>Delete</button></td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>নতুন লেনদেন / Add Transaction</h2><form onSubmit={submitTransaction}><div className="row"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="INCOME">আয় (Income)</option><option value="EXPENSE">ব্যয় (Expense)</option></select><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Donation</option><option>Student Fee</option><option>Salary</option><option>Food</option><option>Utility</option><option>Construction</option><option>Other</option></select></div><input required type="number" min="0" placeholder="টাকার পরিমাণ (₹)" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input placeholder="দাতা / গ্রহণকারীর নাম" value={form.donorName} onChange={e=>setForm({...form,donorName:e.target.value})}/><textarea placeholder="বিবরণ / নোট" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button>সেভ করুন (Save Record)</button></form></section>
 {message&&<p className="message">{message}</p>}
 </main>}
createRoot(document.getElementById('root')).render(<App/>);